---
- hosts: all
  become: true
  gather_facts: true
  vars_files:
    - variables.yml
  roles:
    - geerlingguy.docker
    - geerlingguy.swap
    - geerlingguy.php
    - geerlingguy.composer
    - geerlingguy.nodejs
    - pallxk.code_server

- hosts: all
  name: Development Environment
  gather_facts: true
  tasks:
    # - import_tasks: lando.yml
    - import_tasks: ddev.yml

- hosts: all
  name: ZSH
  tasks:
    - import_tasks: zsh.yml
